### ISSUE TITLE
Use pd.isnull()

### ISSUE THREAD

**Issue by sen1** [ioglesby/intro-data-capstone-musclehub#2]
https://github.com/ioglesby/intro-data-capstone-musclehub/blob/2487b176e0a611d331766f0fea0c25ea40501860/final_project/musclehub-ioglesby.py#L180-L183

The best way to handle the null values is with pandas isnull() method. The missing data in pandas are called `NaN`. So `x!=None` is not the best choice. The best way would be to use isnull(). Read more here: https://chartio.com/resources/tutorials/how-to-check-if-any-value-is-nan-in-a-pandas-dataframe/

**Comment by ioglesby** [comment]
Ahh - thanks..
