### ISSUE TITLE
Whats the purpose of plt.close()?

### ISSUE THREAD

**Issue by sen1** [ioglesby/intro-data-capstone-musclehub#3]
https://github.com/ioglesby/intro-data-capstone-musclehub/blob/2487b176e0a611d331766f0fea0c25ea40501860/final_project/musclehub-ioglesby.py#L516

I see you used plt.close() after each figure. It is not required to call after each plot. 
`plt.close('all')` will close all figures. I sometimes call it at the very beginning of a script if my python environment inherited from another environment with plots. `plt.show()` will pause your code and show all the available plots to you. Once you close them it will go on to the next task. So `plt.close('all')` is basically redundant here.

**Comment by ioglesby** [comment]
Ahh -  I didn't realize it was redundant. Thought I was just being safe. Thanks!
